-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 17:35:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProyectoIntegradorAPI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoIntegradorAPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoIntegradorAPI` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoIntegradorAPI` ;

-- -----------------------------------------------------
-- Table `ProyectoIntegradorAPI`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegradorAPI`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `usr` VARCHAR(45) NULL,
  `passwd` VARCHAR(90) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `usr_UNIQUE` (`usr` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegradorAPI`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegradorAPI`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `lat` VARCHAR(45) NULL,
  `lng` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idlocation`, `user_iduser`),
  INDEX `fk_location_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_location_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `ProyectoIntegradorAPI`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegradorAPI`.`educationRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegradorAPI`.`educationRating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `unlocked` VARCHAR(45) NULL,
  `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `location_idlocation` INT NOT NULL,
  `location_user_iduser` INT NOT NULL,
  PRIMARY KEY (`id`, `location_idlocation`, `location_user_iduser`),
  INDEX `fk_educationRating_location1_idx` (`location_idlocation` ASC, `location_user_iduser` ASC),
  CONSTRAINT `fk_educationRating_location1`
    FOREIGN KEY (`location_idlocation` , `location_user_iduser`)
    REFERENCES `ProyectoIntegradorAPI`.`location` (`idlocation` , `user_iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegradorAPI`.`restaurantRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegradorAPI`.`restaurantRating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `unlocked` VARCHAR(45) NULL,
  `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `location_idlocation` INT NOT NULL,
  `location_user_iduser` INT NOT NULL,
  PRIMARY KEY (`id`, `location_idlocation`, `location_user_iduser`),
  INDEX `fk_restaurantRating_location1_idx` (`location_idlocation` ASC, `location_user_iduser` ASC),
  CONSTRAINT `fk_restaurantRating_location1`
    FOREIGN KEY (`location_idlocation` , `location_user_iduser`)
    REFERENCES `ProyectoIntegradorAPI`.`location` (`idlocation` , `user_iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegradorAPI`.`healthRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegradorAPI`.`healthRating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `unlocked` VARCHAR(45) NULL,
  `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `location_idlocation` INT NOT NULL,
  `location_user_iduser` INT NOT NULL,
  PRIMARY KEY (`id`, `location_idlocation`, `location_user_iduser`),
  INDEX `fk_healthRating_location1_idx` (`location_idlocation` ASC, `location_user_iduser` ASC),
  CONSTRAINT `fk_healthRating_location1`
    FOREIGN KEY (`location_idlocation` , `location_user_iduser`)
    REFERENCES `ProyectoIntegradorAPI`.`location` (`idlocation` , `user_iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegradorAPI`.`mobilityRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegradorAPI`.`mobilityRating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `unlocked` VARCHAR(45) NULL,
  `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `location_idlocation` INT NOT NULL,
  `location_user_iduser` INT NOT NULL,
  PRIMARY KEY (`id`, `location_idlocation`, `location_user_iduser`),
  INDEX `fk_mobilityRating_location1_idx` (`location_idlocation` ASC, `location_user_iduser` ASC),
  CONSTRAINT `fk_mobilityRating_location1`
    FOREIGN KEY (`location_idlocation` , `location_user_iduser`)
    REFERENCES `ProyectoIntegradorAPI`.`location` (`idlocation` , `user_iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegradorAPI`.`crimeRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegradorAPI`.`crimeRating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `unlocked` VARCHAR(45) NULL,
  `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `location_idlocation` INT NOT NULL,
  `location_user_iduser` INT NOT NULL,
  PRIMARY KEY (`id`, `location_idlocation`, `location_user_iduser`),
  INDEX `fk_crimeRating_location1_idx` (`location_idlocation` ASC, `location_user_iduser` ASC),
  CONSTRAINT `fk_crimeRating_location1`
    FOREIGN KEY (`location_idlocation` , `location_user_iduser`)
    REFERENCES `ProyectoIntegradorAPI`.`location` (`idlocation` , `user_iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
